### ISSUE TITLE
ImportError: No module named qgscollapsiblegroupbox

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#101]
Editing UI files raises an error at the next QGIS launch:

```python
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
File "C:/Users/USER/.qgis2/python/plugins\isogeo_plugin_qgis_dev\__init__.py", line 34, in classFactory
from .isogeo import Isogeo
File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/USER/.qgis2/python/plugins\isogeo_plugin_qgis_dev\isogeo.py", line 57, in <module>
from ui.isogeo_dockwidget import IsogeoDockWidget  # main widget
File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/USER/.qgis2/python/plugins\isogeo_plugin_qgis_dev\ui\isogeo_dockwidget.py", line 30, in <module>
os.path.dirname(__file__), 'isogeo_dockwidget_base.ui'))
File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
			    exec(code_string.getvalue(), ui_globals)
File "<string>", line 649, in <module>
File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named qgscollapsiblegroupbox
```

**Comment by Guts** [comment]
This a known specific Windows issue: http://gis.stackexchange.com/questions/164111/plugins-crashing-with-no-module-named-qgsprojectionselectionwidget-in-windows
