### ISSUE TITLE
Impossible d'ouvrir une fiche de métadonnée

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#119]
Pour reproduire :

- Afficher des résultats
- Cliquer sur le premier résultat, la fiche de métadonnée ne s'affiche pas, une erreur python apparaît.

Erreur : 

Traceback (most recent call last):
			  File "C:/Users/valentin.blanlot/.qgis2/python/plugins\isogeo_search_engine\isogeo.py", line 512, in handle_api_reply
			    self.md_display.show_complete_md(parsed_content)
			  File "C:/Users/valentin.blanlot/.qgis2/python/plugins\isogeo_search_engine\modules\metadata_display.py", line 320, in show_complete_md
			    link=self.url_edition)
			TypeError: 'link' is an invalid keyword argument for this function

Fichier log en pièce jointe

[log_isogeo_plugin.txt](https://github.com/isogeo/isogeo-plugin-qgis/files/961796/log_isogeo_plugin.txt)

**Comment by Guts** [comment]
Problème de packaging du plugin en plein milieu d'une modification du code... Version 1.5-beta4 mise à jour directement dans les dépôts QGIS. Choisir "Réinstaller le plugin" sans attendre la prochaine MAJ.
