### ISSUE TITLE
Erreur de certificat SSL à l'ajout d'une couche WMS

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#371]
Message du client :
"On voit bien la liste des WMS proposés, mais erreur quand on les ajoute (certificat autosignés ?)

Une erreur est survenue lors de l'éxécution du code Python:
```

requests.exceptions.SSLError: HTTPSConnectionPool(host='wxs.ign.fr', port=443): Max retries exceeded with url: /f4v4g9qykk6g8go7m4nfey4b/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&layers=ORTHOIMAGERY.ORTHOPHOTOS2006-2010&crs=EPSG:2154&format=image/png&styles=normal&TRANSPARENT=TRUE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wxs.ign.fr', port=443): Max retries exceeded with url: /f4v4g9qykk6g8go7m4nfey4b/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&layers=ORTHOIMAGERY.ORTHOPHOTOS2006-2010&crs=EPSG:2154&format=image/png&styles=normal&TRANSPARENT=TRUE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/thevenon.f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\layer\limitations_checker.py", line 45, in check
    self.layer_adder.adding(layer_info=data_info.get("layer"))
  File "C:/Users/thevenon.f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\layer\add_layer.py", line 437, in adding
    service_details=layer_info[2],
  File "C:/Users/thevenon.f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\layer\add_layer.py", line 274, in add_from_service
    layer_infos = url_builder(api_layer, service_details)
  File "C:/Users/thevenon.f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\layer\geo_service.py", line 686, in build_wms_url
    check_requests = requests.get(url_for_requests)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='wxs.ign.fr', port=443): Max retries exceeded with url: /f4v4g9qykk6g8go7m4nfey4b/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&layers=ORTHOIMAGERY.ORTHOPHOTOS2006-2010&crs=EPSG:2154&format=image/png&styles=normal&TRANSPARENT=TRUE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Version de QGIS : 3.16.4-Hannover Hannover, 654e76b3cb
```

Cordialement"

[fichier log du plugin](https://github.com/isogeo/isogeo-plugin-qgis/files/6516652/log_isogeo_plugin.2.log)

**Comment by SimonSAMPERE** [comment]
@leodarengosse , c'est le même soucis qu'on avait eu avec leur WFS, dans l'urgence j'avais fait une gestion très spécifique donc c'est logique que ça fonctionne pas avec le WMS de l'IGN. Il faudrait que je gère ça plus génériquement mais ça peut prendre un peu de temps.

**Comment by SimonSAMPERE** [comment]
Au choix :
* faire appel à l'API GeoDataProcess pour gérer ce soucis génériquement et pourquoi pas de passer d'owslib
* faire un nouveau fixe équivalent à ce qui avait été fait pour #359

**Comment by SimonSAMPERE** [comment]
Voici la liste des services géographiques actuellement documentés dans le groupe du CD31 et pour lesquels il faudrait développer un fix : 
* WFS : 
  * Service WFS Geoportail : https://wxs.ign.fr/f4v4g9qykk6g8go7m4nfey4b/geoportail/wfs
  * Service de téléchargement des données Open Data - Département de la Haute-Garonne (WFS) : https://geoservices.business-geografic.com/adws/service/wfs/c0a853d2-bc07-11e8-b09f-61c8a2385105 
* WMS : 
  * IGN Service Essentiels WMS Raster Geoportail Publics - France : https://wxs.ign.fr/essentiels/geoportail/r/wms
  * Service WMS Vecteur Geoportail : https://wxs.ign.fr/f4v4g9qykk6g8go7m4nfey4b/geoportail/v/wms
  * Service WMS Raster Geoportail Publics : https://wxs.ign.fr/f4v4g9qykk6g8go7m4nfey4b/geoportail/r/wms
* WMTS :
  * Service de visualisation WMTS Geoportail Publics : https://wxs.ign.fr/f4v4g9qykk6g8go7m4nfey4b/geoportail/wmts/
