### ISSUE TITLE
Geographical filter - canvas

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#9]
Fix the geographical filter based on the canvas extent.

**Comment by Guts** [comment]
When the box is checked, the entire plugin is freezing (except the reset button) and the Python terminal displays:

```python
IOError: [Errno 9] Bad file descriptor
Logged from file isogeo.py, line 601
Traceback (most recent call last):
  File "C:\Users\$USERNAME\Documents\GIS\Plugins\Isogeo\isogeo_search_engine_b2\isogeo.py", line 659, in search
    filters += "&box=" + self.get_canvas_coordinates() + "&rel=" + self.dockwidget.operation.itemData(self.dockwidget.operation.currentIndex()) + " "
  File "C:\Users\$USERNAME\Documents\GIS\Plugins\Isogeo\isogeo_search_engine_b2\isogeo.py", line 852, in get_canvas_coordinates
    currentSRS = QgsCoordinateReferenceSystem(currentEPSG, QgsCoordinateReferenceSystem.EpsgCrsId)
NameError: global name 'QgsCoordinateReferenceSystem' is not defined
```

**Comment by Guts** [comment]
Works only if the map canvas is in EPSG 4326
