### ISSUE TITLE
Erreur python : ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by siglagglo** [isogeo/isogeo-plugin-qgis#96]
Bonjour,
Depuis la mise à du plugin j'ai l'erreur python suivante

```python
2017-02-28T09:03:16	1	Traceback (most recent call last):
			  File "C:/Users/sduceux/.qgis2/python/plugins\isogeo_search_engine\isogeo.py", line 453, in handle_token
			    parsed_content = json.loads(content)
			  File "C:\OSGEO4~1\apps\Python27\lib\json\__init__.py", line 338, in loads
			    return _default_decoder.decode(s)
			  File "C:\OSGEO4~1\apps\Python27\lib\json\decoder.py", line 365, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "C:\OSGEO4~1\apps\Python27\lib\json\decoder.py", line 383, in raw_decode
			    raise ValueError("No JSON object could be decoded")
			ValueError: No JSON object could be decoded
```

Impossible de lancer une requête ou de charger des tables depuis notre base.
Merci

**Comment by Guts** [comment]
A priori, cela intervient lorque la connexion réseau a subi une micro coupure pendant la requête à l'API Isogeo. Une gestion de l'erreur a été ajoutée pour éviter le plantage. En attendant, une solution de contournement peut consister en fermer / réouvrir le plugin (version sur le canal stable) ou décocher/ recocher dans le gestionnaire d'extension (version sur le canal beta).

![qgis_isogeo_json_decoded](https://cloud.githubusercontent.com/assets/1596222/23895382/ca882bfe-08a5-11e7-862b-23c8fed0515f.png)

**Comment by Guts** [comment]
Pas de nouvelles, bonnes nouvelles.
